apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*'
build:
  local:
    # concurrency: 1
    # tryImportMissing: false
    # useDockerCLI: false
    push: false
  artifacts:
    - image: mrnoyce/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        # noCache: false
        # squash: false
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-service
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   rules:
#     - host: ticketing.dev
#       http:
#         paths:
#           - path: /api/users/?(.*)
#             pathType: Prefix
#             backend:
#               service:
#                 name: auth-srv
#                 port:
#                   number: 3000